config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :users, only: [:show, :update]
  resources :tweets do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
    mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def create
    Tweet.create(image: tweet_params[:image], content: tweet_params[:content], user_id: current_user.id)
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  private
  def tweet_params
    params.permit(:image, :content)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @tweets = current_user.tweets.order("created_at DESC")
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

    private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tsubuyaki
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %bodys
    = yield

app/views/shared/_newheader.html.haml
%header.sideheader
  .sideheader-contents
    .sideheader-contents-symbol
      = fa_icon 'twitter'
    %nav.sideheader-contents-menu
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'home', class: "icon"
          = link_to "ホーム", root_path, class: "a"
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'hashtag', class: "icon"
          = link_to "話題を検索", root_path, class: "a"
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'bell', class: "icon"
          = link_to "通知", root_path, class: "a"
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'envelope', class: "icon"
          = link_to "メッセージ", root_path, class: "a"
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'bookmark', class: "icon"
          = link_to "ブックマーク", root_path, class: "a"
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'list-alt', class: "icon"
          = link_to "リスト", root_path, class: "a"
      .menuListItem-path
        .menuListItem-path-link
          = fa_icon 'user-circle', class: "icon"
          = link_to "プロフィール", root_path, class: "a"

app/views/tweets/_header.html.haml
.topbar
  .container
    %ul.navigation
      %li.navigation-home
        .navigation-home-icon
          = fa_icon 'home', class: 'icon'
        %span.navigation-home-text ホーム
      %li.navigation-moments
      %li.navigation-notification
      %li.navigation-dm
    %h1.symbol-icon
      = fa_icon 'twitter', class: 'icon'
    %ul.navigation-right
      %li.search#role
        %form.search-form
          -# ＝ form_with @user, do |f|
          = text_field :name ,"", placeholder:"キーワードを検索", class: "search-input"
          %span.search-icon
            = fa_icon 'search', class: 'icon'
      %li.user-icon
        .dropdown
          %ul.dropdown-usermenu
            %li.dropdown-usermenu-info 
              = current_user.name
            %li.signout-button
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'

app/views/tweets/_leftbox.html.haml
.leftbox
  .leftbox-profile
    .leftbox-profile-link
      .link-mypage 
        = link_to "",user_path(current_user)
    .leftbox-profile-content
      .leftbox-profile-infomation 
        .leftbox-profile-fullname 
          %a.acount-name
          = current_user.name
        %span.leftbox-profile-username
          %a.link-name
            = current_user.linkname
      .follow-list
        %ul.follow-list-stats
          %li.follow-list-people 
            %a.follow-list-peoplelink{href:"https://twitter.com/"}
              %span.follow-list-people-label ツイート
              %span.follow-list-people-value 99
          %li.follow-list-people  
            %a.follow-list-peoplelink{href:"https://twitter.com/"}
              %span.follow-list-people-label フォロー
              %span.follow-list-people-value 100
          %li.follow-list-people 
            %a.follow-list-peoplelink{href:"https://twitter.com/"}
              %span.follow-list-people-label フォロワー
              %span.follow-list-people-value 10000

app/views/tweets/_newtweet.html.haml
%main.maincontent
  .maincontent-center
    .maincontent-center-head
      .maincontent-center-head-backspace
        .maincontent-center-head-backspaceIcon
          = link_to root_path do
            = fa_icon 'arrow-left', class: "icon"
      %h2.maincontent-center-head-username
        = current_user.name
      .maincontent-center-head-all
    .maincontent-center-profile
      .backimage
      .usercontent
        .usercontentInformation
          .userimage
            = image_tag ("profile_photo.png")
          .editprofile
            = link_to "プロフィールを編集", root_path, class: "a"
        .username
          .name
            = current_user.name
          .linkname 
            = current_user.linkname
    .maincontent-center-tweets
      - @tweets.each do |tweet|
        .tweet
          .tweet-content{style:"background-image: url(#{tweet.image})"}
            .tweet-infomation
              %span.fullname
                = tweet.user.name
              %span.link-name
                = tweet.user.linkname
              %small.time 
                = tweet.created_at.strftime("%Y/%m/%d %H:%M")
            .tweet-link
              = fa_icon 'angle-down'
              %ul.more_list
                %li
                  = link_to "削除", "/tweets/#{tweet.id}", method: :delete
            .tweet-content-text 
              = tweet.content
            .tweet-infomation-footer
              .icon-reply
                = fa_icon 'comment', class: 'icon'
              .icon-retweet
                = fa_icon 'retweet', class: 'icon'
              .icon-favarite
                = fa_icon 'heart', class: 'icon'
              .icon-dm
                = fa_icon 'envelope', class: 'icon'

app/views/tweets/_tsubuyaki.html.haml
.content
	.timeline-tweet-box
		.home-tweet-box
			= form_with(model: @tweet, url: tweets_path, local: true) do |f|
				= f.text_field :content, class: 'form__image', placeholder: '今どうしてる？'
				= f.label :image, class: 'icon' do
					= fa_icon 'image'
					= f.file_field :image, class: 'hidden'
				= f.submit 'ツイート', class: 'form__submit'
	.tweet
		= render partial: 'tweet', collection: @tweets

app/views/tweets/_tweet.html.haml
.tweet-content
  .tweet-infomation
    %span.fullname
      = tweet.user.name
    %span.link-name
      = tweet.user.linkname
    %small.time 
      = tweet.created_at.strftime("%Y/%m/%d %H:%M")
  .tweet-content-text{style:"background-image: url(#{tweet.image})"}
    = tweet.content
  .tweet-link
    = fa_icon 'angle-down'
    %ul.more_list
      %li
        = link_to "削除", "/tweets/#{tweet.id}", method: :delete
  .tweet-infomation-footer
    .icon-reply
      = fa_icon 'comment', class: 'icon'
    .icon-retweet
      = fa_icon 'retweet', class: 'icon'
    .icon-favarite
      = fa_icon 'heart', class: 'icon'
    .icon-dm
      = fa_icon 'envelope', class: 'icon'

app/views/tweets/create.html.haml
.contents.row
  .success
    %h3
      投稿が完了しました。
    %a.btn{:href => "/tweets"} 投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.contents.row
  .success
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/tweets/index.html.haml
= render partial: 'header'
.page-outer
  .wrapper
    = render partial: 'leftbox'
    = render partial: 'tsubuyaki'

app/views/users/show.html.haml
.wrapper
  = render 'shared/newheader'
  = render 'tweets/newtweet'